### ISSUE TITLE
Forum -> Forum Rules or Notices  BB codes dosent work/unformated text always

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1064]
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18429055/abf9b25c-78d1-11e6-81a4-3f15be9b6906.JPG)

plz send me a feedback what i have to change

**Comment by RobiNN1** [comment]
Reinstall forum, all working

**Comment by RobiNN1** [comment]
yes   and strat new thread, reply to thread not working

**Comment by Catzenjaeger** [comment]
lol i cant install it again and again ...i lost all my data . the forum works but the BB codes not

**Comment by RobiNN1** [comment]
bbcods working on my site, after reinstall works all

**Comment by Catzenjaeger** [comment]
hmn but i lost all my data  when i reinstall. what codes i can replace? new install again and again is not a solution .. guess one or more files are wrong .. not more. **Can we solve it without a installation??????**

**Comment by RobiNN1** [comment]
Reinstall It's currently the only solution

**Comment by Catzenjaeger** [comment]
but why? was here a table change in the last days?  no i guess not my complete install is 2  days old  Install only the infusion " forum " or all?

**Comment by meangczac** [comment]
No need reinstall. You want to format Forum Notice?

**Comment by meangczac** [comment]
Catz, please click at this link - https://github.com/php-fusion/PHP-Fusion/commit/f6cea597eeed547f7cb4ead90b425e3f282297be and see how it is solved.

**Comment by Catzenjaeger** [comment]
hmn i have change the 2 files but my BB codes don't work again.  When i click on it the site reload only. Text what i write inside will be stored and shown ..... but not formate.

**Comment by Catzenjaeger** [comment]
not solved .. dosent work my on my space. i have replace the files
