### ISSUE TITLE
language setting in admin allows stacking

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#520]
I pushed saved twice, it keeps incrementing the sublinks eventho they exist.

![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11496500/9cd05d4e-9812-11e5-8ef4-bc336a176de3.jpg)

**Comment by meangczac** [comment]
Try again. I just fixed.

**Comment by JoakimFalk** [comment]
Fresh install. new sync I can still reproduce the issue with removal of the language and then adding it back. I guess the removal ain´t clearing the site links from it´s lang?
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11514411/a320f8fa-9878-11e5-9054-ea4d4a014b18.jpg)

**Comment by meangczac** [comment]
Aiyah.. yeah maybe. I'll check later. Need to reinstall the whole system. I thought I did it correctly.

**Comment by meangczac** [comment]
Still doing template work, really heavy stuff atm. Will fix when I'm able to

**Comment by meangczac** [comment]
Not solved. still creating a lot of link.

**Comment by JoakimFalk** [comment]
![stacking](https://cloud.githubusercontent.com/assets/4210004/11976810/479d917c-a97c-11e5-8504-c7f76a248118.jpg)
